### ISSUE TITLE
number is not a function

### ISSUE THREAD

**Issue by lewanthony** [cs4278-2015/assignment4-handin#13]
#ChangeLog
Copied test-temp/folder1/test.txt to test-temp/folder2/test.txt
      ✓ should correctly create changelog.txt file
      1) "after each" hook

  2) should correctly call add log to changelog

  38 passing (113ms)
  2 failing

  1)  "after each" hook:
     Uncaught TypeError: number is not a function
  

  2) lib/sync #ChangeLog should correctly call add log to changelog:
     Error: ENOENT, no such file or directory 'test-temp/folder1'
      at Error (native)
      at Object.fs.readdirSync (fs.js:761:18)
      at Object.localFs.list (lib/sync/sync.js:10:15)
      at getDirectoryInfo (lib/sync/sync.js:216:13)
      at Object.compare (lib/sync/sync.js:168:5)
      at Object.checkForChanges (lib/sync/sync-driver.js:87:10)
      at Context.<anonymous> (test/test.js:458:21)

**Comment by mcgowacr** [comment]
Fixed in master, setTimeout was implemented improperly. The changelog tests should now delay the appropriate amount of time and finish successfully.
